log:
  stdout: true
  level: info

persistence:
  defaultStore: sqlite-default
  visibilityStore: sqlite-visibility
  numHistoryShards: 4
  datastores:
    sqlite-default:
      sql:
        pluginName: "sqlite"
        databaseName: "/var/lib/temporal/db/default.db"
        connectProtocol: "tcp"
        maxConns: 1
        maxIdleConns: 1
    sqlite-visibility:
      sql:
        pluginName: "sqlite"
        databaseName: "/var/lib/temporal/db/visibility.db"
        connectProtocol: "tcp"
        maxConns: 1
        maxIdleConns: 1

global:
  membership:
    maxJoinDuration: 30s
    broadcastAddress: "0.0.0.0"

services:
  frontend:
    rpc:
      grpcPort: 7233
      membershipPort: 6933
      bindOnIP: "0.0.0.0"
      httpPort: 8233

  matching:
    rpc:
      grpcPort: 7235
      membershipPort: 6935
      bindOnIP: "0.0.0.0"

  history:
    rpc:
      grpcPort: 7234
      membershipPort: 6934
      bindOnIP: "0.0.0.0"

  worker:
    rpc:
      grpcPort: 7236
      membershipPort: 6936
      bindOnIP: "0.0.0.0"

clusterMetadata:
  enableGlobalNamespace: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "frontend"
      rpcAddress: "localhost:7233"

dcRedirectionPolicy:
  policy: "noop"

publicClient:
  hostPort: "localhost:7233"
